version: "3.8"
services:
  front:
    build: front/
    container_name: front
    ports:
      - "80:80"
    volumes:
      - ./front/dist/:/var/www/html
    links:
      - api
  api:
    build: api/
    container_name: api
    ports:
      - "3333:80"
    volumes:
      - ./api/:/var/www/html
    env_file:
      - "./api/.env"
    links:
      - db
  db:
    image: mysql:5.7.22
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - dihgg-datavolume:/var/lib/mysql-dihgg
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dihgg
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
volumes:
  dihgg-datavolume:
